### ISSUE TITLE
cannot reproduce the seg results.

### ISSUE THREAD

**Issue by chensjtu** [SamsungLabs/SPIn-NeRF#4]
I have tried the DS_NeRF/run_nerf.py and find that the mask generated by semantic nerf is worse than mask provided. Does there any suggestions? 
<img width="1309" alt="image" src="https://github.com/SamsungLabs/SPIn-NeRF/assets/38242929/24727928-71b3-42a4-a76e-41d52be3f807">

**Comment by chensjtu** [comment]
I think I got the key, this is caused by dilate. Maybe you can provide instructions for the Mvseg since I cannot get the right results using code in MVSEG. The mask seems to be broken。

**Comment by xiyufeng2** [comment]
I got the samilar problem. When I train my own data, how to get the initial masks(eq: 'statue/images_2/label', which seems to be a total black mask) ?

**Comment by ashmrz** [comment]
Hi. Sorry for the late reply; this repo is no longer maintained. For creating your own dataset, I suggest following the sample data we provide under https://drive.google.com/drive/folders/1N7D4-6IutYD40v9lfXGSVbWrd47UdJEC. For generating masks, you can use any multi-view or image segmentation method of your choice. Only note that after getting the masks, you have to arrange them in the same format as the SPIn-NeRF dataset. The masks provided might seem black with your image viewer, since the viewer expects the masks to have values between 0 and 255, but they are actually either 0 and 1, so not visible in the 255 scale.
